version: '3.8'

services:
  equipo1:
    image: alpine:latest
    container_name: equipo1
    # Usamos sleep para mantener el contenedor encendido, 
    # ya que Alpine por defecto no ejecuta ningún servicio continuo.
    command: sleep infinity 
    networks:
      - mi_red_practica

  equipo2:
    image: alpine:latest
    container_name: equipo2
    command: sleep infinity
    networks:
      - mi_red_practica

  # ==========================================
  # HONEYPOT
  # ==========================================
  honeypot:
    image: cowrie/cowrie:latest
    container_name: honeypot_cowrie
    volumes:
      - volumen_logs_cowrie:/home/cowrie/cowrie/var/log/cowrie 
    ports:
      - "22:2222" 
      - "2223:2223" 
    networks:
      - mi_red_practica

  # ==========================================
  # SURICATA
  # ==========================================
    
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: "service:honeypot"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./suricata/config:/etc/suricata
      - ./suricata/logs:/var/log/suricata
    command: -i eth0
    restart: always

# ==========================================
  # WAZUH SIEM STACK (Single-Node)
  # ==========================================
  
  # 1. Wazuh Indexer (Base de datos)
  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.8.0
    container_name: wazuh.indexer
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g" # Asignamos 1GB de RAM (ajusta si tienes más)
    ports:
      - "9200:9200"
    volumes:
      - wazuh_indexer_data:/var/lib/wazuh-indexer
    networks:
      - mi_red_practica

  # 2. Wazuh Manager (El analizador)
  wazuh.manager:
    image: wazuh/wazuh-manager:4.8.0
    container_name: wazuh.manager
    depends_on:
      - wazuh.indexer
    ports:
      - "1514:1514" # Puerto para que los agentes envíen logs
      - "1515:1515" # Puerto para el registro de agentes
      - "55000:55000" # API de Wazuh
    volumes:
      - wazuh_manager_data:/var/ossec/data
      # ¡CONEXIÓN CON COWRIE! Leemos los logs del honeypot en modo solo lectura (ro)
      - volumen_logs_cowrie:/var/ossec/logs/cowrie_logs:ro 
    networks:
      - mi_red_practica

  # 3. Wazuh Dashboard (La interfaz web)
  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.8.0
    container_name: wazuh.dashboard
    depends_on:
      - wazuh.indexer
      - wazuh.manager
    ports:
      - "443:5601" # Acceso a la web por HTTPS en tu localhost:443
    volumes:
      - wazuh_dashboard_data:/usr/share/wazuh-dashboard/data
    networks:
      - mi_red_practica

# ==========================================
# REDES Y VOLÚMENES
# ==========================================
networks:
  mi_red_practica:
    driver: bridge

volumes:
  volumen_logs_cowrie:
  wazuh_indexer_data:
  wazuh_manager_data:
  wazuh_dashboard_data: