version: '3.8'

services:
  database:
    image: vulhub/opentsdb:2.4.0
    container_name: database
    # Usamos sleep para mantener el contenedor encendido, 
    # ya que Alpine por defecto no ejecuta ningún servicio continuo.
    command: sleep infinity
    ports:
      - "4242:4242"
    networks:
      - business_network

  electron:
   image: vulhub/electron:wine
   command: bash /docker-entrypoint.sh
   volumes:
    - ./src:/project
    - ./build:/build
    - ./docker-entrypoint.sh:/docker-entrypoint.sh
  web:
   image: nginx:1
   volumes:
    - ./build:/usr/share/nginx/html
   ports:
    - "8080:80"

  internal_server: #TO DO: CONECTAR CON WAZUH
    image: cowrie/cowrie:latest
    container_name: internal_server
    volumes:
      - volumen_logs_cowrie:/home/cowrie/cowrie/var/log/cowrie # <-- Usamos un volumen interno
    ports:
      - "22:2222" # <--- ¡EL CAMBIO MÁGICO! Tu puerto 22 apunta al 2222 de Cowrie
      - "2223:2223" 
    networks:
      - business_network
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: "service:honeypot"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./suricata/config:/etc/suricata
      - ./suricata/logs:/var/log/suricata
    command: -i eth0
    restart: always

# Aquí declaramos la red personalizada a la que se conectarán
networks:
  business_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/24

# ¡NUEVO! Le decimos a Docker que cree y gestione este volumen
volumes:
  volumen_logs_cowrie: